# -*- coding: utf-8 -*-
# **************************************************************************
# *
# * Authors:     Scipion Team
# *
# * National Center of Biotechnology, CSIC, Spain
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
from os.path import join, abspath

from emtable import Table

from tomo.objects import TiltSeries, TiltSeriesM, TiltImage

# TS motioncorr - star file fields
WRP_MOVIE_NAME = '_wrpMovieName'
WRP_ANGLE_TILT = '_wrpAngleTilt'
WRP_AXIS_ANGLE = '_wrpAxisAngle'
WRP_DOSE = '_wrpDose'
# Per-tilt brightness measure = **median pixel value of the motion-corrected aligned average.
# The value is never read back by any downstream tool
WRP_AVERAGE_INTENSITY = '_wrpAverageIntensity'
# Per-tilt junk-coverage measure = **fraction (0–1) of the tilt image's pixels flagged as "mask"
# by the BoxNet2 neural network** (carbon edges, contamination, gold, other artifacts). This
# tomostar column is never read back.
WRP_MASKED_FRACTION = '_wrpMaskedFraction'
tsStarFileFields = [
    WRP_MOVIE_NAME,
    WRP_ANGLE_TILT,
    WRP_AXIS_ANGLE,
    WRP_DOSE,
    WRP_AVERAGE_INTENSITY,
    WRP_MASKED_FRACTION,
]


def writeTsStar(tsM: TiltSeriesM, outputStarFile: str):
    """It creates a star file for a given tilt-series.
    It is expected to be executed after WarpTools fs_motion_and_ctf
    with the option --out_averages.
    """
    tsMTable = Table(columns=tsStarFileFields)
    acq = tsM.getAcquisition()
    for tiM in tsM.iterItems(orderBy=TiltImage.TILT_ANGLE_FIELD):
        tsMTable.addRow(
            abspath(tiM.getFileName()),
            - tiM.getTiltAngle(),  # Warp inverts the tilt angles at this level
            acq.getTiltAxisAngle(),
            tiM.getAcquisition().getDoseInitial(),  # In the example of the tutorial, the tilt = 0 has dose = 0,
            # so it is the dose pre-specimen
            0.,  # See variable definition above
            0.,  # See variable definition above
        )
    with open(outputStarFile, 'w') as fid:
        fid.write('# Generated by Scipion\n')
        # Write the STAR file
        tsMTable.writeStar(fid)
